### ISSUE TITLE
How is zdotdir different from zephyr?

### ISSUE THREAD

**Issue by kohane27** [getantidote/zdotdir#3]
Hello there. Thank you for creating all these tools! I'm currently migrating from oh-my-zsh and found out two of yours tools: zdotdir and [zephyr](https://github.com/mattmc3/zephyr). I got confused and would highly appreciate it if you could provide a little explanation.

Thank you again!

**Comment by mattmc3** [comment]
This project only exists to provide example Zsh configurations for antidote users, or for when someone submits an antidote bug and I want to provide that person a working Zsh config to resolve their issue.

Zephyr is completely separate project that has nothing to do with antidote specifically, but works well with antidote. It's a mini-framework similar to [zsh-utils](https://github.com/belak/zsh-utils), and borrows a lot from Prezto without all the dependancies. When using parts of frameworks like Oh My Zsh and Prezto piecemeal with a plugin manager, you go a bit outside their intended use. That can make it difficult to use only the parts you like without also pulling in all the dependencies. Projects like Zephyr are meant to help ease that transition for users of projects like Prezto into a world where you can compose you own ideal Zsh config from only the parts you like/need using lightweight, fast, simple plugins without big framework dependancies.
