### ISSUE TITLE
CTRL-R doesn't work

### ISSUE THREAD

**Issue by marcinjahn** [getantidote/zdotdir#4]
CTRL-R should fire up reverse search. I installed zsh, and applied zdotdir configurations, did nothing else. CTRL-R does nothing in my case. I tried using different terminal emulator apps: Gnome Terminal, Tilix, Black Box. All of them lack reverse search.
How could it be fixed?

**Comment by mattmc3** [comment]
Sorry, maybe there's some confusion - this project isn't meant to be a working Zsh config (if you want that, check out my personal [zdotdir](https://github.com/mattmc3/zdotdir)). This project is to show how you might use antidote to configure your Zsh config. If you want a good set of keybindings, I might suggest using `mattmc3/zephyr path:plugins/editor` or `sorin-ionescu/prezto path:modules/editor`.

**Comment by marcinjahn** [comment]
Hmm, the readme says "Consider it a starter kit for antidote and Zsh", so I assumed it'd be a good config to use :slightly_smiling_face: 
I tried applying your config instead, but that came with its own set of issues such as `/home/mnj/.config/zsh/.zshenv:1: job table full or recursion limit exceeded` being printed on every new terminal.

Unfortunatly, `mattmc3/zephyr path:plugins/editor` doesn't seem to readd CTRL+R (or CTRL+A, which also doesn't work).
It feels like zsh configuration is some kind of rabbit hole :slightly_smiling_face:
