### ISSUE TITLE
Custom overrides

### ISSUE THREAD

**Issue by trevg22** [getantidote/zdotdir#7]
Hello, I really like this project it is an amazing starting point for what can be a little daunting. Would it be possible to add more custom files, such as a file for variable overrides and alias overrides, like you have for plugins, this would avoid merge conflicts for forks.

**Comment by mattmc3** [comment]
The point of this repo isn't really to be a whole Zsh config kickstarter (aka: $ZDOTDIR), but rather to show you how to create a composable config yourself just with just `antidote` and a well structured `.zsh_plugins.txt`. It's also a clean ZDOTDIR for my own testing when there's an issue reported to antidote and it would be easier to show a solution via a code branch than to type up a solution. So, in that vein, I won't be doing anything like this in this project.

However, I have considered creating a Zsh kickstarter project. I just haven't had the time. I would welcome a PR though.
